### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#10]
Hi,

Is it possible to load the a list with having a default autoWhere(). For example, I want the list to do a where season_id = 1 by default for example. 

Is that possible?

**Comment by maikealame** [comment]
Yes
Add:
`use Auto\Facades\Auto;`
Call:
`Auto::setDefaultField( "column", "value" );`
If you don't want filter by view, use this and any url filter param will be ignored by column:
`Auto::setField( "column","value");`

**Comment by asivaneswaran** [comment]
Hi,

Thanks for your answer. I get an error:
```
array_merge(): Argument #1 is not an array`
at HandleExceptions->handleError(2, 'array_merge(): Argument #1 is not an array', '/home/vagrant/Code/kin-ball-v4/vendor/maikealame/laravel-auto/src/Auto.php', 68, array('column' => 'teams.season_id', 'value' => 4))
at array_merge(null, array('teams.season_id' => 4))
in Auto.php (line 68)
```

Here is the code:
`
Auto::setDefaultField('teams.season_id', Season::current()->first()->id);`

Thanks,

**Comment by maikealame** [comment]
confirm if you get last version 0.4.4

**Comment by asivaneswaran** [comment]
These are the versions:

`maikealame/auto-where                 0.2.15  PHP helper to automatically create sql where conditions
maikealame/laravel-auto               0.4.4   Laravel helper to make almost everything for your project
`

Thanks,

**Comment by maikealame** [comment]
Using Laravel v5.4 ?

**Comment by asivaneswaran** [comment]
Yeah: `laravel/framework                     v5.4.27 The Laravel Framework.`

**Comment by asivaneswaran** [comment]
It's in the file:  `laravel-auto/src/Auto` line 93:
```Request::has("filter[$column]") ?: Request::merge(["filter"=>array_merge(Request::get("filter"),[$column=>$value])]);```

The `Request::get("filter")` is null when visiting the page: `admin/team`

**Comment by maikealame** [comment]
Ok, try new version 0.4.4.1

**Comment by asivaneswaran** [comment]
It's working!
