### ISSUE TITLE
Autowhere are not filtering

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#11]
Hi,

This is my url:
`member?filter%5Bmembers.first_name%5D=steph&filter%5Bmembers.gender%5D=F&sort=members.gender&order=asc`

But this is the sql I get:
`"select * from `members` where  true  and `members`.`deleted_at` is null order by `members`.`gender` asc"`

Here is the code:

```
dd(Member::autoWhere(["columns" => ["gender" => "equal"]])->autoSort(['members.last_name', 'asc'])->toSql());
```

Thanks,

**Comment by maikealame** [comment]
Try
`member?filter%5Bfirst_name%5D=steph&filter%gender%5D=F&sort=gender&order=asc`
for a test

**Comment by asivaneswaran** [comment]
Ah, it works. I removed the table name!

Thanks,
