### ISSUE TITLE
Make the icons clickable instead of the column name

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#2]
Hey,

It's me again. I was wondering if you were thinking to add a way to make the icons of the columns clickable. Right now, to sort, you have to click on the column name (Name, Age, etc.) but would it be possible to make the arrows next to the names sort? And then make the anchor text not a link anymore. Right now, the config 'clickable_icon' true but there is no way to make the anchor text, just a text.

THanks,

THanks,

**Comment by maikealame** [comment]
You can choise in `config.php` if icon is clickable or not, but not only icon.
See `'clickable_icon' => true,`
It go to https://github.com/maikealame/laravel-auto/projects/1#card-3117715

**Comment by maikealame** [comment]
Ok, try using `'clickable_icon' => "only"` in 0.3.15

**Comment by asivaneswaran** [comment]
Nice work! Thanks for the quick update!
