### ISSUE TITLE
 @autopages() doesnt switch page on the bootstrap list

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#6]
Hey,

So another small bug. I am using the : ` @autopages($list)`  but the pages with `autopages()` isnt changing. It always stays at 1.

Thanks,

**Comment by maikealame** [comment]
See how many rows are you bring from query and how many you paginate in config file ou forcing in controller. If you paginate more than your records, the paginate buttons not appear.
I can't understand what error is it, if is js or php, send me a print and url after changing page.

**Comment by asivaneswaran** [comment]
https://gyazo.com/66491d682db12a9383815ab033534e37

As you can see, I am on page 3 but the selected page at the bottom is page 1.

Thanks,

**Comment by maikealame** [comment]
Are using `@autopagesasync` ?

**Comment by asivaneswaran** [comment]
Yes and when I remove`§@autopageasync` it works. This is my template for my tables:
```
@extends('layouts.admin.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-md-1 pull-right">
                        <a href="{{ $create_route }}" class="btn btn-success btn-circle btn-lg waves-effect"><i class="fa fa-plus"></i> </a>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table color-table inverse-table table-striped">
                                <thead>
                                    @yield('table_header')
                                </thead>
                                <tbody>
                                    @yield('table_body')
                                </tbody>
                            </table>
                        </div>
                    </div>

                    @autopages($list)
                </div>
            </div>
        </div>
    </div>
@endsection

@push('inline_scripts')
    @autopagesasync('.table-responsive table')
@endpush
```

**Comment by maikealame** [comment]
So, the problem is simple:

like see in the docs
```
@autopagesasync('.panel-table')
@autopagesasync(['.panel-table tbody', '.panel-table .panel-footer'])
@autopagesasync(['.panel-table tbody', '.panel-table .panel-footer'], false)
```
**param[0]: replace selector - required, string or array**
**param[1]: url change flag - default: true**

when async, the first argument is the selector to replace, so if you replace only `'.table-responsive table'` you forget pagination of page loaded async, with pagination correctly actived. you can use in two ways generally: 
`@autopagesasync('.white-box')` to replace panel and all content inside
or
`@autopagesasync(['.table-responsive table', '.pagination'])` an array with many selectors to replace.

**Comment by asivaneswaran** [comment]
Oh wow, yeah I didn't realise it was in div

Thanks,
