### ISSUE TITLE
Autowhere filters not matching for select

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#7]
Hi,

I have a select box for auto filtering like this:

```
@inject('tableService', 'App\Services\TableService')

<select name="teams.season_id" class="form-control input-filter">
    @foreach($tableService->seasonsSelect(true) as $id => $season)
        <option value="{{ $id }}" selected="@autowherefilter('teams.season_id', $id)">{{ $season }}</option>
    @endforeach
</select>
```

The filter works fine, like the data is the correct data. But the `selected=` is set on every options. Like this: 
![screen shot 2017-06-19 at 6 27 36 pm](https://user-images.githubusercontent.com/2759350/27308527-024560b6-551d-11e7-9583-b4f64c87792e.png)

The fix should be like this:
```
<option value="{{ $id }}" @autowherefilter('teams.season_id', $id)>{{ $season }}</option>
```

**Comment by maikealame** [comment]
Is a error from the docs, seems like the browser interpreter `selected=""` the same if it is `selected`, boths are true. Quickly solution, replace
`selected="@autowherefilter('teams.season_id', $id)"`
to 
`@autowherefilter('teams.season_id', $id)`

**Comment by maikealame** [comment]
I will update the docs to fix it

**Comment by maikealame** [comment]
Fixed.
