### ISSUE TITLE
AutoWhere() for string enum column

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#8]
Hi,

So I have a Enum column `['M', 'F']` and I am trying to use the autoWhere on it.

In my url, it says: `team?filter%5Bteams.gender%5D=3`

But, it doesn't filter. This is the sql:
```
select `teams`.* from `teams` left join `categories` on `categories`.`id` = `teams`.`category_id` left join `divisions` on `divisions`.`id` = `teams`.`division_id` left join `seasons` on `seasons`.`id` = `teams`.`season_id` where true and `teams`.`deleted_at` is null order by `categories`.`name` asc limit 10 offset 0
```

I am not sure, what is wrong? If I change the url to `teams.slug`, it filters... So I am not sure if it's because it's a enum column

**Comment by maikealame** [comment]
[Updated] Yes, it's possible because  this type is not mapped yet. I will add soon. For now, use the columns parameter to overwrite the type to other compatible. Maybe this:
->autoWhere([ "columns" => [ "teams.gender" => "equal" ] ])
or
Auto::columns( "teams.gender", "equal" );

I miss put in docs all possibilities for columns. I will update too.

**Comment by asivaneswaran** [comment]
Hi,

I added it, but it still doesn't work:

```return $query->autoWhere(["columns" => ["teams.gender" => "equal"]])->autoSort(['categories.name', 'asc'])->autoPaginate();```

And the url is:
`team?filter%5Bteams.gender%5D=M`

**Comment by maikealame** [comment]
Ok, the query stays same ?

**Comment by asivaneswaran** [comment]
This is the query:
```
select `teams`.* from `teams` left join `categories` on `categories`.`id` = `teams`.`category_id` left join `divisions` on `divisions`.`id` = `teams`.`division_id` left join `seasons` on `seasons`.`id` = `teams`.`season_id` where  true  and `teams`.`deleted_at` is null order by `categories`.`name` asc limit 10 offset 
```

**Comment by maikealame** [comment]
I update the package, there's an error when adapt to laravel. Fixed now. Download and try again.

**Comment by asivaneswaran** [comment]
It works now.

Thanks!
