### ISSUE TITLE
Connect to database

### ISSUE THREAD

**Issue by Redagou** [maikealame/laravel-auto#9]
I didn't found the PHP file where I put my database informations?

**Comment by maikealame** [comment]
This package not use DB, it's create sql automatically with Eloquent ORM, so the DB is the same you defined for laravel.
https://laravel.com/docs/5.4/database
Follow instalation steps on docs https://maikealame.github.io/laravel-auto#how-to-install and you ready to start, the only config stay in config/laravel-auto.php after publish this package.
